version: '3.8'

services:
  mongodb:
    image: mongo:8-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: arun0009
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - sam_network
    volumes:
      - mongodb_data:/data/db

networks:
  sam_network:
    driver: bridge

volumes:
  mongodb_data: